### ISSUE TITLE
Figure out var forks based on data-parent-branch?

### ISSUE THREAD

**Issue by that0n3guy** [brittanydionigi/form-forker#42]
I ran across this plugin today.  It works quite well so far.  Thanks for making it public.

One thing I noticed was that you have to add a `fork` class to everything you want to fork.  Couldn't this be simplified by basing it off the info found in all the different `data-parent-branch` data-tags?

So instead of using `$('#branching-form').forkable('.fork');` to get this to work.  You can specify `$('#branching-form').forkable();`.

The `.fork` could be made optional (if not set or set null it would just use  `data-parent-branch`)

Anyways.  Not a big deal I just thought it might simplify it for the end user :+1:

**Comment by brittanydionigi** [comment]
Yep, good point. Adding this to a list of things to refactor, but also feel free to submit a pull request!  There are a couple functionality/testing things I'd like to get to before coming back to this. Thanks for pointing it out.
